name: 🐛 Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce?
      placeholder: |
        1. Step 1
        2. Step 2
        3. See error
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code sample
      render: typescript

  - type: input
    id: version
    attributes:
      label: Package version
      placeholder: e.g., 2.0.1
    validations:
      required: true
