name: 🐛 Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: dropdown
    id: scope
    attributes:
      label: 📦 Scope
      options:
        - Core SDK
        - Agent Runtime
        - LLM Integration
        - Monitoring
        - Smart Contracts
        - Documentation
        - Examples
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 🐛 Description
      description: Clear description of the bug
      placeholder: What's the bug?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 📝 Steps to Reproduce
      placeholder: |
        1. Initialize SDK with...
        2. Call method...
        3. See error

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected
      placeholder: What should happen?

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual
      placeholder: What actually happened?

  - type: textarea
    id: code
    attributes:
      label: 💻 Code
      render: typescript
      placeholder: |
        import { SomniaAgentKit } from 'somnia-agent-kit';
        // Your code here

  - type: textarea
    id: logs
    attributes:
      label: 📋 Logs
      render: shell
      placeholder: Paste error logs here

  - type: input
    id: version
    attributes:
      label: 📦 Version
      placeholder: e.g., 2.0.1

  - type: dropdown
    id: environment
    attributes:
      label: 🖥️ Environment
      options:
        - Node.js
        - Browser
        - React Native
        - Other

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional
      placeholder: Screenshots, related issues, etc.
