name: 📚 Documentation
description: Report an issue with documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation!

  - type: dropdown
    id: type
    attributes:
      label: Documentation Issue Type
      options:
        - Missing documentation
        - Incorrect information
        - Unclear explanation
        - Typo or grammar
        - Broken link
        - Missing example
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue?
      placeholder: e.g., README.md, API_REFERENCE.md, examples/ai-agent-ollama
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's Wrong?
      description: Describe the issue with the documentation
      placeholder: The documentation says... but it should say...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: How should we fix this?
      placeholder: I suggest changing it to...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful

