name: 📚 Documentation
description: Report documentation issues
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - Missing documentation
        - Incorrect information
        - Unclear explanation
        - Typo or grammar
        - Broken link
        - Missing example
        - Outdated content
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Which file/section?
      placeholder: e.g., README.md, API_REFERENCE.md line 123
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's Wrong?
      description: Describe the issue
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: How to fix it?
      placeholder: Change "..." to "..."
