name: 📚 Documentation
description: Report documentation issues
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: dropdown
    id: type
    attributes:
      label: 📝 Type
      options:
        - Missing documentation
        - Incorrect information
        - Unclear explanation
        - Typo or grammar
        - Broken link
        - Missing example
        - Outdated content
        - Other

  - type: input
    id: location
    attributes:
      label: 📍 Location
      placeholder: e.g., README.md line 123, API_REFERENCE.md section "Agent Runtime"

  - type: textarea
    id: issue
    attributes:
      label: ❌ Issue
      description: What's wrong?
      placeholder: The documentation says... but it should say...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: ✅ Suggestion
      description: How to fix it?
      placeholder: Change "..." to "..."

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional
      placeholder: Screenshots, links, etc.
