name: ✨ Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: dropdown
    id: scope
    attributes:
      label: 📦 Scope
      options:
        - Core SDK
        - Agent Runtime
        - LLM Integration
        - Monitoring
        - Smart Contracts
        - Documentation
        - Examples
        - CLI
        - Other

  - type: textarea
    id: problem
    attributes:
      label: 💡 Problem
      description: What problem does this solve?
      placeholder: I'm frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: ✨ Solution
      description: How should it work?
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: 💻 Example
      render: typescript
      placeholder: |
        import { SomniaAgentKit } from 'somnia-agent-kit';
        // Example of how the feature would work

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives
      placeholder: Other solutions I've considered...

  - type: dropdown
    id: priority
    attributes:
      label: ⚡ Priority
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking my project

  - type: checkboxes
    id: contribute
    attributes:
      label: 🤝 Contribution
      options:
        - label: I'm willing to help implement this

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional
      placeholder: Links, mockups, etc.
