name: 🔧 Improvement
description: Improve existing functionality
title: "[Improvement]: "
labels: ["improvement", "enhancement"]
body:
  - type: dropdown
    id: scope
    attributes:
      label: 📦 Scope
      options:
        - Core SDK
        - Agent Runtime
        - LLM Integration
        - Monitoring
        - Smart Contracts
        - Documentation
        - Examples
        - Performance
        - Developer Experience
        - Error Messages
        - CLI
        - Other

  - type: dropdown
    id: type
    attributes:
      label: 🎯 Type
      options:
        - Performance optimization
        - Better error messages
        - API simplification
        - Documentation clarity
        - Code quality
        - Developer experience
        - Testing
        - Other

  - type: textarea
    id: current
    attributes:
      label: 📌 Current
      description: How does it work now?
      placeholder: Currently, when I...

  - type: textarea
    id: proposed
    attributes:
      label: ✨ Proposed
      description: How should it work instead?
      placeholder: It would be better if...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: 💻 Example
      render: typescript
      placeholder: |
        // Current way
        
        // Proposed way

  - type: textarea
    id: benefits
    attributes:
      label: 🎁 Benefits
      placeholder: |
        - Easier to use
        - Better performance
        - Clearer API

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional
      placeholder: Any other context
