name: ❓ Question
description: Ask a question
title: "[Question]: "
labels: ["question"]
body:
  - type: dropdown
    id: category
    attributes:
      label: 📚 Category
      options:
        - Getting Started
        - Installation
        - Configuration
        - Core SDK
        - Agent Runtime
        - LLM Integration
        - Smart Contracts
        - Monitoring
        - CLI
        - Best Practices
        - Other

  - type: textarea
    id: question
    attributes:
      label: ❓ Question
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: 🔍 What I've Tried
      placeholder: |
        - I tried...
        - I also tried...

  - type: textarea
    id: code
    attributes:
      label: 💻 Code
      render: typescript
      placeholder: |
        // Related code (if any)

  - type: textarea
    id: additional
    attributes:
      label: 📎 Additional
      placeholder: Any other context
