name: ❓ Question
description: Ask a question
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Related code (optional)
      render: typescript
